### ISSUE TITLE
NoSuchMethodError for wrapAndThrow

### ISSUE THREAD

**Issue by antoinelauzon-bell** [FasterXML/jackson-databind#4591]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Hi,

We are using the [jackson-bean-validation](https://github.com/unbroken-dome/jackson-bean-validation) extension to do validations based on annotations. It seems that [a recent change](https://github.com/FasterXML/jackson-databind/commit/dae483b7cb29cff679d538a91f204eeadbff39a3) in the version 2.17 modified the signature of a method that is used by this extension. This is causing a "NoSuchMethodError":

```
Caused by: java.lang.NoSuchMethodError: 'void org.unbrokendome.jackson.beanvalidation.ValidatingBeanDeserializer.wrapAndThrow(java.lang.Throwable, java.lang.Object, java.lang.String, com.fasterxml.jackson.databind.DeserializationContext)'
```

The library extends `BeanDeserializer` (see [ValidatingBeanDeserializer](https://github.com/unbroken-dome/jackson-bean-validation/blob/master/src/main/java/org/unbrokendome/jackson/beanvalidation/ValidatingBeanDeserializer.java#L33)) that provides the `wrapAndThrow` method.

I know that the library hasn't been update since 3 years but it seems to me that the signature of this public method shouldn't have been modified.

### Version Information

2.17.0

### Reproduction

See details above.

### Expected behavior

Be able to update this dependency (not a major release) without impacting other dependencies.

**Comment by pjfanning** [comment]
* jackson-bean-validation is not affiliated with this project
* it was built with Jackson 2.11
https://github.com/unbroken-dome/jackson-bean-validation/blob/master/build.gradle.kts#L21

So contact the maintainer of jackson-bean-validation if you want a version of jackson-bean-validation that works with Jackson 2.17.

**Comment by cowtowncoder** [comment]
Agreed with what @pjfanning states -- this is something with jackson-bean-validation's compatibility with newer Jackson versions, and they should be able to resolve it.
(and if need be work with us if there is some compatibility issue that needs addressing).
