### ISSUE TITLE
Crash on Android < 26 on ObjectMapper constructor

### ISSUE THREAD

**Issue by AlvaroBrey** [FasterXML/jackson-databind#4653]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

After upgrading the `jackson-databind` version, I've found a crash on the `ObjectMapper` constructor. This only happens on Android API versions older than 26 (android 8.0)

Here's the stacktrace:

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/BootstrapMethodError;
                                                                                                    	at com.fasterxml.jackson.databind.util.ExceptionUtil.isFatal(ExceptionUtil.java:51)
                                                                                                    	at com.fasterxml.jackson.databind.util.ExceptionUtil.rethrowIfFatal(ExceptionUtil.java:31)
                                                                                                    	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:70)
                                                                                                    	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:402)

```

### Version Information

2.17.2

2.8.3 does not present this problem

### Reproduction

Run a sample Android app that calls the `ObjectMapper` constructor, on any device with API level < 26 

### Additional context

The crash seems to have been introduced by https://github.com/FasterXML/jackson-databind/pull/3827, as before the exception was likely caught and ignored. I have been unable to find the underlying exception that is rethrown.

**Comment by pjfanning** [comment]
Android SDK 26 is the minimum expected version.

https://github.com/FasterXML/jackson-databind/blob/2.18/pom.xml#L53

**Comment by AlvaroBrey** [comment]
Ouch, thanks! I see that 2.13 is the last version I can use. Cheers!

**Comment by cowtowncoder** [comment]
Required min Android SDK versions also listed on README:

https://github.com/FasterXML/jackson-databind?tab=readme-ov-file#android
