### ISSUE TITLE
2.16 breaks deserialization of polymorphic types using @JsonSubTypes

### ISSUE THREAD

**Issue by LouisXhaferi** [FasterXML/jackson-databind#4233]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

With the update of jackson-databind from `2.15.3` to `2.16.0`, deserialization of polymorphic types seems to have broken.

In combination with Kotlin (`1.9.20`) and Spring Boot (`3.2.0`), I am no longer able to use polymorphic types as JSON request bodies, leading to HTTP 500, due to deserialization failures.

Trying to deserialize throws this exception (Stracktrace attached below): 
```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonTypeInfo$Value
```

I am honestly not sure, why/where this bug was caused, but as increasing a minor version of jackson-databind leads to it, I'll start off by reporting this here.

I have not tried it without using Spring Boot, but have directly used an ObjectMapper instance.

### Version Information

2.16.0

### Reproduction

For reproduction purposes, I've created a small spring boot based example repo.
https://github.com/LouisXhaferi/jackson-2-16-deser-failure

The `main` branch contains the failing `2.16.0` version, while the branch `2.15.3` contains the working old version.

Anyways, here a short overview of what should work in `2.15.3`, but breaks in `2.16.0`

```kotlin
/**
 *
 * Endpoint consuming polymorphic object and returning the same
 *
 */
sealed interface PolymorphicType {
    data class A(val value: String) : PolymorphicType
    data class B(val value: Int) : PolymorphicType
}

@PostMapping("/polymorphic")
fun polymorphic(@RequestBody body: PolymorphicType) = body


/**
 *
 * Test Case
 *
 */
@Test
fun `polymorphic should return successfully`() {
    val request = A("Hello World")

    val response = testRestTemplate.postForEntity(
        "http://localhost:$port/polymorphic",
        request,
        Controller.PolymorphicType::class.java
    )

    assertThat(response.statusCode.value()).isEqualTo(200)
    assertThat(response.body is A).isTrue
    assertThat(response.body).isEqualTo(request)
}
```

The same error is raised directly using an ObjectMapper

```kotlin
@Test
fun `should deserialize polymorphic type`() {
    val json = """
            {
              "type": "TypeA",
              "value": "Hello World"
            }
        """.trimIndent()

    val result = objectMapper.readValue(json, PolymorphicType::class.java)

    assertThat(result is PolymorphicType.A).isTrue
}
```

### Expected behavior

Deserialization of polymorphic objects should be successful, as it was in 2.15.3.

### Additional context

Stacktrace example

```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonTypeInfo$Value
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findPolymorphicTypeInfo(JacksonAnnotationIntrospector.java:670)
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector._findTypeResolver(JacksonAnnotationIntrospector.java:1579)
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findTypeResolver(JacksonAnnotationIntrospector.java:677)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findTypeResolver(AnnotationIntrospectorPair.java:253)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findTypeResolver(AnnotationIntrospectorPair.java:253)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findTypeResolver(AnnotationIntrospectorPair.java:251)
	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.createTypeSerializer(BasicSerializerFactory.java:312)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:857)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:330)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1572)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1061)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:483)
	at org.springframework.http.converter.AbstractGenericHttpMessageConverter$1.writeTo(AbstractGenericHttpMessageConverter.java:94)
	at org.springframework.http.client.SimpleClientHttpRequest.executeInternal(SimpleClientHttpRequest.java:83)
	at org.springframework.http.client.AbstractStreamingClientHttpRequest.executeInternal(AbstractStreamingClientHttpRequest.java:70)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:879)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:781)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:529)
	at org.springframework.boot.test.web.client.TestRestTemplate.postForEntity(TestRestTemplate.java:454)
	at com.mercedesbenz.jackson216deserfailure.ControllerTest.polymorphic should return successfully(ControllerTest.kt:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:218)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:214)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:139)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:119)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:94)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:89)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonTypeInfo$Value
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 105 more
```

Louis Xhaferi <louis.xhaferi@mercedes-benz.com> on behalf of Mercedes-Benz Tech Innovation GmbH.
[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by yihtserns** [comment]
When running `gradlew dependencies`, seems like there's mixed versions of Jackson dependencies (`2.16.0` + `2.15.3`).

Unfortunately I'm not pro at Gradle so I'm not sure how you can force all of them to be `2.16.0`.

**Comment by LouisXhaferi** [comment]
Oh no, that actually might be a (or the) problem, since I explicitly imported `jackson-databind` (probably because of some past vulnerability that needed mitigating).
Updating all jackson components to 2.16.0 would either (a) take a lot of more work or (b) spring boot updating the versions themselves.

Something in 2.16.0 is probably not fully compatible with 2.15.3, leading to this weird behavior.

**Comment by LouisXhaferi** [comment]
I'll try recreating my issue with a non-spring boot project, but I have the suspicion that it might have been my mistake.

**Comment by yihtserns** [comment]
Maybe this can help: https://blog.gradle.org/alignment-with-gradle-module-metadata

**Comment by LouisXhaferi** [comment]
Yeah, as expected, I cannot reproduce this issue with a project without mixed dependencies. If all jackson components are 2.16.0. 🤦🏻 

I think this issue can be closed. Sorry.

**Comment by JooHyukKim** [comment]
> I think this issue can be closed. Sorry.

@LouisXhaferi Could you close the issue?

**Comment by LouisXhaferi** [comment]
> > I think this issue can be closed. Sorry.
> 
> @LouisXhaferi Could you close the issue?

Yup, of course! Thanks for the help, guys! 🙏🏻

**Comment by OlivierFortier** [comment]
I just lost 3 days trying to figure out what was wrong in my code, reading the documentation over and over again and trying all the possible ways... 😵

Just saw this issue and I simply downgraded to 2.15.3.. everything is working perfectly 🥳

**Comment by JooHyukKim** [comment]
> I just lost 3 days trying to figure out what was wrong in my code, reading the documentation over and over again and trying all the possible ways... 😵

Sorry to hear that 🥲

**Comment by cowtowncoder** [comment]
@OlivierFortier So far it does not seem like 2.16.0 broke anything tho: originally reported issue was and is due to installing different minor versions of Jackson components. So while it is unfortunate you spend lots of time trying to troubleshoot it, you probably have a version problem remaining somewhere.
This assuming that you experience the same problem.

**Comment by OlivierFortier** [comment]
> @OlivierFortier So far it does not seem like 2.16.0 broke anything tho: originally reported issue was and is due to installing different minor versions of Jackson components. So while it is unfortunate you spend lots of time trying to troubleshoot it, you probably have a version problem remaining somewhere; downgrade wouldn't fix that problem, wherever it is. This assuming that you experience the same problem.
> 
> I also doubt Spring Boot would have specific issue with 2.16.0 over 2.15.3: but Jackson core components MUST have same minor version; they are not mix-and-match (although sometimes, some versions MAY work -- but there's no guarantee).

I explained it poorly. I know it's just a matter of having matching component versions, I meant that I just choose to downgrade jackson-databind to put all the jackson components on the same version as the spring provided ones instead of setting the versions of each component individually. 

I just lost those 3 days because I didn't bother checking if there could be a problem with the versions instead of my own code 😅

**Comment by cowtowncoder** [comment]
@OlivierFortier Ah. That makes sense -- thank you for explanation!

**Comment by yihtserns** [comment]
I just happen to finish reading about Spring Boot Gradle Plugin for my day job, when I noticed that your sample project uses the same thing - [according to the doc](https://docs.spring.io/spring-boot/docs/3.2.0/gradle-plugin/reference/htmlsingle/#managing-dependencies.dependency-management-plugin.customizing), here's how you can safely force the version of Jackson dependencies to `2.16.0`:
```
extra["jackson-bom.version"] = "2.16.0"
```

**Comment by susanw1** [comment]
I'm getting a regression bug appearing as I upgrade from 2.15.4 to 2.16.0, which is similar to this but with different error:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: No Object Id found for an instance of `com.fasterxml.jackson.module.mrbean.generated.net.zscript.model.datamodel.MiniModuleDef$NumberTypeDefinition`, to assign to property '@id'
 at [Source: (URL); line: 6, column: 1] (through reference chain: com.fasterxml.jackson.module.mrbean.generated.net.zscript.model.datamodel.MiniModuleDef$ModuleModel["commands"]->java.util.ArrayList[0]->com.fasterxml.jackson.module.mrbean.generated.net.zscript.model.datamodel.MiniModuleDef$CommandModel["typeDefinition"])

```
I'm pretty sure I don't have mismatched subcomponent versions (or if I do, then IntelliJ and .m2/repository aren't showing them). No Spring, but YamlFactory and MrBean are in play.

Would you prefer I open a new issue, or detail it here?

**Comment by cowtowncoder** [comment]
@susanw1 We rarely open closed issued, so new please. If it can be triggered with JSON instead of YAML, then file at jackson-databind: if it requires YAML (likely), at jackson-dataformats-text.
