### ISSUE TITLE
Regression with custom `@JsonUnwrapped` deserializer from 3.0 to 3.1

### ISSUE THREAD

**Issue by kistlers** [FasterXML/jackson-databind#6001]
### Search before asking

- [x] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

@JsonUnwrapped on Java record components behaves differently between Jackson databind 3.0.x and 3.1.x when the unwrapped value uses a custom ValueDeserializer that implements unwrappingDeserializer(...).

With Jackson databind 3.0.x, the custom unwrapping deserializer receives the expected flattened JSON fields.

With Jackson databind 3.1.x, the custom unwrapping deserializer is still invoked and receives the correct NameTransformer, but the JsonParser content passed to deserialize(...) is an empty object {}. As a result, the unwrapped value cannot be deserialized.

More context is in the reproducer repo: https://github.com/kistlers/jackson-3-unwrapped-regression/blob/main/README.md

Multiple changes were released with 3.1 that relate to JsonUnwrapped, but I cannot se what exactly relates to my issue:
- https://github.com/FasterXML/jackson-databind/issues/650
- https://github.com/FasterXML/jackson-databind/issues/1497
- https://github.com/FasterXML/jackson-databind/issues/1811

### Version Information

3.1.3

### Reproduction

I created a full reproducer repo:
https://github.com/kistlers/jackson-3-unwrapped-regression

The Readme describes the full steps of reproduction and a test that works in 3.0.4 and fails in 3.1.3

### Expected behavior

This behaviour should still work in 3.1

**Comment by cowtowncoder** [comment]
Fixed by assuming that deserializer that does not indicate having any properties (in 3.1 meaning it's not a sub-type of `BeanDeserializerBase`; and in 3.2 does not implement `ValueDeserializer.collectAllPropertyNamesTo()` (or collects 0 properties) will get ALL properties sent (no name-based filtering aside from `@JsonView` and explicit ignorals).

**Comment by kistlers** [comment]
Thank you for the quick fix!
I'll check out that base class and method you mentioned for 3.1 and 3.2, respectively. Sounds like they might improve my deserializer.

**Comment by cowtowncoder** [comment]
Yes, esp. in 3.2; 3.1.x difficult to make use since check is based on sub-classing (could not make api change in patch release).
