### ISSUE TITLE
`InvalidFormatException` for `JsonToken.VALUE_EMBEDDED_OBJECT`

### ISSUE THREAD

**Issue by zigzago** [FasterXML/jackson-databind#1730]
jackson 2.9.0

I got InvalidFormatException. It works fine in 2.8

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.bson.types.ObjectId` from native value (`JsonToken.VALUE_EMBEDDED_OBJECT`) of type `org.bson.types.ObjectId`: incompatible types
 at [Source: org.litote.bson4jackson.io.LittleEndianInputStream@69a2b3b6; pos: 5] (through reference chain: org.litote.kmongo.model.Friend["_id"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdNativeValueException(DeserializationContext.java:1568)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdNativeValue(DeserializationContext.java:975)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromEmbedded(BeanDeserializerBase.java:1471)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:519)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:416)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1265)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:325)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3079)

```
 in BeanDeserializerBase line 1469 I think that instead
`!_beanType.getClass().isInstance(value)`
It should be` !_beanType.getRawClass().isInstance(value)`

**Comment by cowtowncoder** [comment]
Ok. I think you are probably right. Thank you for reporting this.

I would need a reproduction here. Ideally stand-alone against databind, but if need be I can manually verify against `bson4jackson` too.
If this is difficult to do, I may be able to cobble something together using `TokenBuffer`, but if you have something that would be of great help.

**Comment by zigzago** [comment]
Ok I've just pushed an upgrade to jackson 2.9.0 for this project: https://github.com/Litote/bson4jackson

- clone the project
- run the tests https://github.com/Litote/bson4jackson/blob/master/src/test/java/org/litote/bson4jackson/deserializers/BsonDeserializersTest.java

-> the test "symbol" fails with this stacktrace:

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.litote.bson4jackson.types.Symbol` from native value (`JsonToken.VALUE_EMBEDDED_OBJECT`) of type `org.litote.bson4jackson.types.Symbol`: incompatible types
 at [Source: org.litote.bson4jackson.io.LittleEndianInputStream@1e6d1014; pos: 9] (through reference chain: org.litote.bson4jackson.deserializers.BsonDeserializersTest$TC$S["obj"])

	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdNativeValueException(DeserializationContext.java:1568)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdNativeValue(DeserializationContext.java:975)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromEmbedded(BeanDeserializerBase.java:1471)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3058)
	at org.litote.bson4jackson.deserializers.BsonDeserializersTest.generateAndParse(BsonDeserializersTest.java:97)
	at org.litote.bson4jackson.deserializers.BsonDeserializersTest.symbol(BsonDeserializersTest.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) 
```

HTH
