### ISSUE TITLE
FasterXML version 2.9.0 : JaxbAnnotationIntrospector throws java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.getType()

### ISSUE THREAD

**Issue by pnarumanchi** [FasterXML/jackson-databind#1865]
Hello,

I am working on an upgrade project from Spring 4.0 to Spring 4.2.5 on JBoss EAP7.0. The earlier fasterxml version was 2.3.0. Upgraded to 2.9.0. 

Maven Dependency tree is below 
`+- com.ahm:ahm_ngt_converter_common:jar:2.0.0:compile
+- com.ahm:ahm_ngt_converter_data:jar:2.0.0:compile
+- com.ahm:ahm_ngt_converter_services:jar:2.0.0:compile
|  +- org.drools:drools-spring:jar:6.0.0.Beta2:compile
|  |  +- org.kie:kie-api:jar:6.0.0.Beta2:compile
|  |  +- org.kie:kie-internal:jar:6.0.0.Beta2:compile
|  |  +- org.drools:drools-core:jar:6.0.0.Beta2:compile
|  |  |  \- org.mvel:mvel2:jar:2.1.4.Final:compile
|  |  +- org.drools:drools-compiler:jar:6.0.0.Beta2:compile
|  |  |  +- org.antlr:antlr-runtime:jar:3.3:compile
|  |  |  +- org.antlr:antlr:jar:3.3:compile
|  |  |  +- org.antlr:stringtemplate:jar:3.2.1:compile
|  |  |  \- org.eclipse.jdt.core.compiler:ecj:jar:3.5.1:compile
|  |  +- org.drools:drools-decisiontables:jar:6.0.0.Beta2:compile
|  |  |  +- org.drools:drools-templates:jar:6.0.0.Beta2:compile
|  |  |  \- org.apache.poi:poi-ooxml:jar:3.9:compile
|  |  |     +- org.apache.poi:poi:jar:3.9:compile
|  |  |     \- org.apache.poi:poi-ooxml-schemas:jar:3.9:compile
|  |  |        \- org.apache.xmlbeans:xmlbeans:jar:2.3.0:compile
|  |  |           \- stax:stax-api:jar:1.0.1:compile
|  |  \- com.thoughtworks.xstream:xstream:jar:1.4.3:compile
|  |     +- xmlpull:xmlpull:jar:1.1.3.1:compile
|  |     \- xpp3:xpp3_min:jar:1.1.4c:compile
|  +- org.jibx:jibx-bind:jar:1.3.1:compile
|  |  +- org.apache.bcel:bcel:jar:6.0:compile
|  |  +- log4j:log4j:jar:1.2.16:compile (version managed from 1.2.17)
|  |  +- org.apache.ant:ant:jar:1.8.4:compile
|  |  |  \- org.apache.ant:ant-launcher:jar:1.8.4:compile
|  |  \- com.thoughtworks.qdox:qdox:jar:1.12.1:compile
|  +- org.jibx:jibx-run:jar:1.3.1:compile
|  |  \- xpp3:xpp3:jar:1.1.3.4.O:compile
|  \- org.jibx:jibx-extras:jar:1.3.1:compile
|     +- dom4j:dom4j:jar:1.6.1:compile
|     |  \- xml-apis:xml-apis:jar:1.0.b2:compile
|     \- org.jdom:jdom:jar:1.1.3:compile
+- org.slf4j:slf4j-api:jar:1.7.5:compile
+- javax:javaee-api:jar:8.0:provided
|  \- com.sun.mail:javax.mail:jar:1.5.5.redhat-1:provided (version managed from 1.6.0)
|     \- javax.activation:activation:jar:1.1.1.redhat-5:provided (version managed from 1.1)
+- org.apache.httpcomponents:httpclient:jar:4.5.4:compile
|  +- org.apache.httpcomponents:httpcore:jar:4.4.7:compile
|  +- commons-logging:commons-logging:jar:1.2:compile
|  \- commons-codec:commons-codec:jar:1.10:compile
+- org.springframework:spring-webmvc:jar:4.2.5.RELEASE:compile
|  \- org.springframework:spring-expression:jar:4.2.5.RELEASE:compile
+- org.springframework:spring-aop:jar:4.2.5.RELEASE:compile
|  \- aopalliance:aopalliance:jar:1.0:compile
+- org.springframework:spring-tx:jar:4.2.5.RELEASE:compile
+- org.springframework:spring-jdbc:jar:4.2.5.RELEASE:compile
+- org.springframework:spring-orm:jar:4.2.5.RELEASE:compile
+- org.springframework:spring-web:jar:4.2.5.RELEASE:compile
+- org.springframework:spring-core:jar:4.2.5.RELEASE:compile
+- org.springframework:spring-aspects:jar:4.2.5.RELEASE:compile
|  \- org.aspectj:aspectjweaver:jar:1.8.8:compile
+- org.springframework:spring-context:jar:4.2.5.RELEASE:compile
+- org.springframework:spring-context-support:jar:4.2.5.RELEASE:compile
+- org.springframework:spring-beans:jar:4.2.5.RELEASE:compile
+- org.springframework:spring-test:jar:4.2.5.RELEASE:test
+- org.springframework.integration:spring-integration-core:jar:4.2.5.RELEASE:compile
|  +- org.springframework.retry:spring-retry:jar:1.1.2.RELEASE:compile
|  \- org.springframework:spring-messaging:jar:4.2.5.RELEASE:compile (version managed from 4.2.4.RELEASE)
+- org.springframework.integration:spring-integration-jms:jar:4.2.5.RELEASE:compile
|  \- org.springframework:spring-jms:jar:4.2.5.RELEASE:compile (version managed from 4.2.4.RELEASE)
+- org.springframework.integration:spring-integration-stream:jar:4.2.5.RELEASE:compile
+- org.springframework.integration:spring-integration-mail:jar:4.2.5.RELEASE:compile
+- org.springframework.integration:spring-integration-file:jar:4.2.5.RELEASE:compile
+- org.springframework.integration:spring-integration-http:jar:4.2.5.RELEASE:compile
+- org.springframework.integration:spring-integration-xml:jar:4.2.5.RELEASE:compile
|  +- org.springframework.ws:spring-xml:jar:2.2.4.RELEASE:compile (version managed from 2.2.2.RELEASE)
|  \- org.springframework:spring-oxm:jar:4.2.5.RELEASE:compile (version managed from 4.2.4.RELEASE)
+- org.springframework.integration:spring-integration-ws:jar:4.2.5.RELEASE:compile
|  \- org.springframework.ws:spring-ws-core:jar:2.2.4.RELEASE:compile (version managed from 2.2.2.RELEASE)
+- org.springframework.integration:spring-integration-jdbc:jar:4.2.5.RELEASE:compile
+- joda-time:joda-time:jar:2.1:compile
+- org.apache.commons:commons-collections4:jar:4.1:compile
+- commons-io:commons-io:jar:2.6:compile
+- org.apache.commons:commons-lang3:jar:3.6:compile
+- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
+- com.fasterxml.jackson.core:jackson-databind:jar:2.9.0:compile
|  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.0:compile
+- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar:2.9.0:compile
+- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.0:compile
|  \- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.0:compile
+- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.0:compile
+- org.hibernate:hibernate-entitymanager:jar:5.0.9.Final-redhat-1:provided
+- org.hibernate:hibernate-validator:jar:5.2.4.Final-redhat-1:provided
|  +- javax.validation:validation-api:jar:1.1.0.Final-redhat-1:provided (version managed from 1.1.0.Final)
|  \- com.fasterxml:classmate:jar:1.1.0:provided
+- net.sf.ehcache:ehcache:jar:2.10.4:compile
+- org.hibernate:hibernate-ehcache:jar:5.0.9.Final-redhat-1:compile
|  +- org.jboss.logging:jboss-logging:jar:3.3.0.Final-redhat-1:compile (version managed from 3.3.0.Final)
|  \- net.sf.ehcache:ehcache-core:jar:2.4.3:compile
+- org.hibernate:hibernate-core:jar:5.0.9.Final-redhat-1:provided (scope not updated to compile)
|  +- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final-redhat-1:provided (version managed from 1.0.0.Final)
|  +- antlr:antlr:jar:2.7.7:provided
|  +- org.apache.geronimo.specs:geronimo-jta_1.1_spec:jar:1.1.1:provided
|  +- org.jboss:jandex:jar:2.0.0.Final:provided
|  \- org.hibernate.common:hibernate-commons-annotations:jar:5.0.1.Final:provided
+- org.hibernate:hibernate-c3p0:jar:5.0.9.Final-redhat-1:provided
|  \- com.mchange:c3p0:jar:0.9.2.1:provided
|     \- com.mchange:mchange-commons-java:jar:0.2.3.4:provided
+- net.objecthunter:exp4j:jar:0.4.8:compile
+- org.apache.logging.log4j:log4j-1.2-api:jar:2.10.0:compile
|  +- org.apache.logging.log4j:log4j-api:jar:2.10.0:compile
|  \- org.apache.logging.log4j:log4j-core:jar:2.10.0:compile
+- junit:junit:jar:4.10:test
|  \- org.hamcrest:hamcrest-core:jar:1.1:test
+- org.javassist:javassist:jar:3.22.0-GA:compile
\- com.google.code.gson:gson:jar:2.8.0:compile
`

I am using JAXBAnnotationIntrospector and JacksonIntrospector with the ObjectMapper. The code snippet is below
`AnnotationIntrospector introspector = new JaxbAnnotationIntrospector(TypeFactory.defaultInstance());		this.setAnnotationIntrospector(introspector);		
AnnotationIntrospector secondary = new JacksonAnnotationIntrospector();
this.setAnnotationIntrospector(new AnnotationIntrospectorPair(introspector, secondary));
this.configure(DeserializationFeature.UNWRAP_ROOT_VALUE, true);			this.enable(SerializationFeature.WRAP_ROOT_VALUE);
this.configure(SerializationFeature.WRAP_ROOT_VALUE, true);
this.setSerializationInclusion(JsonInclude.Include.NON_NULL);
this.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)		this.enable(MapperFeature.USE_WRAPPER_NAME_AS_PROPERTY_NAME);`

When I test my usecase, I see the below error
`Caused by: java.lang.IllegalStateException: Cannot process message
	at org.springframework.integration.util.MessagingMethodInvokerHelper.processInternal(MessagingMethodInvokerHelper.java:333)
	at org.springframework.integration.util.MessagingMethodInvokerHelper.process(MessagingMethodInvokerHelper.java:155)
	at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:93)
	... 11 more
Caused by: java.lang.NoSuchMethodError: **com.fasterxml.jackson.databind.introspect.AnnotatedMember.getType()Lcom/fasterxml/jackson/databind/JavaType;**
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector._fullSerializationType(JaxbAnnotationIntrospector.java:1545)
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector._findContentAdapter(JaxbAnnotationIntrospector.java:1496)`

When I googled for any reference, I found #1539 but I am using version 2.9.0 so the resolution didn't help.

I appreciate if you could help me with a resolution or correct me if my approach was wrong?

Thanks,
Padma.

**Comment by cowtowncoder** [comment]
Please try first with the latest patch version, `2.9.3`, of the minor version you want -- there is no benefit from trying to use earlier ones.
That alone should not cause the issue but is the general best practice for Jackson versions.

Other than this what the error suggest is that version of `jackson-databind` (which has `AnnotatedMember`) is different than what `jackson-module-jaxb-annotations` was compiled against.
If Maven dependencies are used as runtime dependencies, there should not be any problem, but perhaps it is possible that somehow classpath also has an older version (like 2.3.0?).
The order of jars in case of conflict is unpredictable so older versions of classes may be loaded, and that is one thing that could explain error you are seeing.

**Comment by pnarumanchi** [comment]
Okay. I tried with 2.9.3. I see the same error even after.

There is no 2.3.0 jars in the classpath. I removed the 2.3.0 jars before posting here to confirm that there is no conflict. In fact, this time, I removed the dependency folder "fasterxml" in the maven home directory and downloaded only 2.9.3 jars.

**Comment by pnarumanchi** [comment]
More information.

My POJOs have xml and json annotations. The old code had JAXBIntrospector alone. After upgrade to 2.9.0, that did not work. ObjectMapper couldn't read the input json; threw exception. I had to add @XMLTransient annotation in the POJO to the elements that doesn't exist in the input json. It looks weird to me but adding that annotation helped. Now, I get the error while serializing the response. I read in one of the forums that both JaxBIntrospector and JacksonIntrospector should be registered with the mapper. So, I added both of them but now I get the error again at ObjectMapper.readValue().

I tried different approaches.


When I use only JAXBIntrospector,

**Comment by cowtowncoder** [comment]
Annotation handling has not really changed much, with respect to set up, between 2.3 and 2.9.
So if lone JAXBAnnotationIntrospector worked, it should still work.

But exception that you see has nothing to do with actual processing: it would be thrown by classloader when trying to load code that refers to incorrect signature of a class from another jar.
And specifically class from `jackson-module-jaxb-annotations` referring to a method of class `JavaType` within `jackson-databind`.

This is the problem regarding that exception: you have inconsistent versions of two libraries. I can not say why this is the case nor figure out: you need to find it out on your environment.

**Comment by pnarumanchi** [comment]
I verified and made sure that no other minor version jars are in the classpath. I got the same error with 2.9.3, 2.9.0, 2.7.*,

With 2.8.*, I got an error for a different missing field - "com.fasterxml.jackson.databind.introspect.AnnotatedField.isTransient()"

I only got my application working with 2.6.0.

**Comment by pnarumanchi** [comment]
Every time I changed the version, I made sure to clear the dependencies and made sure that no jars exist on classpath.

**Comment by cowtowncoder** [comment]
Regardless, this is due to incompatible deployed jars, as read by classloader when attempting to run code. It would not be possible to compile such versions with missing methods. This is not something that compatible minor versions would have.

So there is unfortunately nothing I can do here from my end at this point.

Methods are added in minor versions (but not removed) so this hints at direction of version discrepancy.

**Comment by vnktshp** [comment]
Hi, I am facing same exception when trying to upgrade Spring boot from 1.3.1 to 1.5.9

Jackson versions are 2.8.10 and there are no old or duplicate jars in the class path.

Any help on the resolution?

org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.getType()Lcom/fasterxml/jackson/databind/JavaType;
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:115)
	at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59)
	at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.mod_cluster.undertow.metric.RunningRequestsHttpHandler.handleRequest(RunningRequestsHttpHandler.java:69)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:285)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:264)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:175)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:324)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:803)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cowtowncoder** [comment]
@vnktshp Same thing applies: you have incompatible versions in classpath, either across Jackson components, or code compiled against Jackson (version of Jersey might expect newer version of Jackson).

**Comment by lpxp** [comment]
remvoe the jackson folder under classpath and resolved the issue
