### ISSUE TITLE
Return type `<T extends JsonNode> T` breaks type inference

### ISSUE THREAD

**Issue by emlun** [FasterXML/jackson-databind#2537]
Hi! I encountered some problems after I upgraded jackson-databind from 2.9.9.3 to 2.10: some of my calls to `ObjectNode.set` now cause compilation errors. I've reduced it to this minimal example:

```java
package org.example;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.util.function.Function;

public class JacksonCompilationFailure {

    static ObjectMapper objectMapper = new ObjectMapper();
    static JsonNodeFactory jsonFactory = JsonNodeFactory.instance;

    static ObjectNode editValue(ObjectNode value, String name, JsonNode v) throws JsonProcessingException {
        return ((ObjectNode) objectMapper.readTree(objectMapper.writeValueAsString(value)))
            .set(name, v);
    }

    static <T extends JsonNode> ObjectNode editValue(ObjectNode value, String name, Function<JsonNode, T> updater) throws JsonProcessingException {
        ObjectNode cpy = (ObjectNode) objectMapper.readTree(objectMapper.writeValueAsString(value));
        return cpy.set(name, updater.apply(cpy.get(name)));
    }

    public static void main(String[] args) throws JsonProcessingException {
        ObjectNode a = (ObjectNode) objectMapper.readTree("{\"foo\": \"bar\"}");
        ObjectNode b = editValue(a, "foo", jsonFactory.objectNode().set("bar", jsonFactory.textNode("boo")));
    }

}
```

This fails with the compilation error:

```
Error:(27, 24) java: reference to editValue is ambiguous
  both method editValue(com.fasterxml.jackson.databind.node.ObjectNode,java.lang.String,com.fasterxml.jackson.databind.JsonNode) in org.example.JacksonCompilationFailure and method <T>editValue(com.fasterxml.jackson.databind.node.ObjectNode,java.lang.String,java.util.function.Function<com.fasterxml.jackson.databind.JsonNode,T>) in org.example.JacksonCompilationFailure match
```

As best as I can tell, this is because the [`set` method returns `<T extends
JsonNode>
T`](https://github.com/FasterXML/jackson-databind/blob/2.10/src/main/java/com/fasterxml/jackson/databind/node/ObjectNode.java#L385)
where `T` is not constrained by the arguments, so the compiler can't infer the
type `T` in the above case. If you explicitly specify the type parameter in the
call to `set`, or bind it to a variable before passing it as an argument, it
compiles and runs fine:

```java
        ObjectNode b = editValue(a, "foo", jsonFactory.objectNode().<ObjectNode>set("bar", jsonFactory.textNode("boo")));
        // or alternatively:
        ObjectNode o = jsonFactory.objectNode().set("bar", jsonFactory.textNode("boo"));
        ObjectNode b = editValue(a, "foo", o);

```

`ObjectNode.setAll` has the same issue, and possibly some other methods as well.

Maybe this is considered fixed, because the return type on master is `ObjectNode` which should not cause these issues, but [the 2.11 branch also has the same `<T extends JsonNode> T` return type](https://github.com/FasterXML/jackson-databind/blob/2.11/src/main/java/com/fasterxml/jackson/databind/node/ObjectNode.java#L385) as 2.10 does.

The original context in which I encountered this is [here, in Scala](https://github.com/Yubico/java-webauthn-server/blob/master/webauthn-server-core/src/test/scala/com/yubico/webauthn/RelyingPartyRegistrationSpec.scala#L1025), which also fails to disambiguate which overload of `editAttestationObject` to call. This causes a few more issues with type inference in Scala, but I'm not sure Scala support is a major concern for the project.

**Comment by cowtowncoder** [comment]
Ok. So, the change between 2.9 and 2.10 was from return type of `JsonNode` to `<T extends JsonNode>`; issue is #2339.  That issue should have longer context, but here's summary of how I remember it.

The main limitation which is still here for rest of 2.x is that we can not change signature of `set()` (and related) methods from sub-optimal `JsonNode` into what it really should be, `ObjectNode`: doing so would break many things esp. due to transitive dependencies. Change of return value in this case is source-compatible but NOT binary-compatible; a particularly nasty combination that did causes issues with some of Jackson 1.x minor versions.
Return type has been fixed for 3.0 (`master`).

What is possible in 2.x is to add generic type bounds, since erased type is still the same, so code compiled against 2.9 will have no trouble linking against 2.10 (or vice versa).
None of tests had compilation problems but then again tests are limited in what they cover.
And unfortunately issue was not reported during pre-release candidate phase.

So, at this point this may be something that can not really be changed: it can't be changed for 2.10.x itself (2.10.0 is out and in use; patches should not break such usage). But it is unclear if there would be benefit to undo change for 2.11 either.

**Comment by emlun** [comment]
Gotcha. Let's consider this fixed for 3.0, then. I'll agree it probably makes more sense to keep the feature in than revert it, as the conditions where this happens seem quite narrow. I think the above kind of overloaded method signatures was the only way I managed to trigger it.

**Comment by cowtowncoder** [comment]
Yeah. Had I known of existence of the new problem, tho, I might not have bothered with the overload but it is what it is.
