### ISSUE TITLE
Support `@JsonSerializeAs` annotation

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#5476]
With https://github.com/FasterXML/jackson-annotations/issues/324 a new general Jackson annotation, `@JsonSerializeAs` was added: it needs to be supported by databind.

This means, basically, that following 2 cases should be equivalent

```
@com.fasterxml.jackson.databind.annotation.JsonSerialize(as = ValueInterface.class)
public class Value {
}
```

```
@com.fasterxml.jackson.annotation.JsonSeserializeAs(value = ValueInterface.class)
public class Value {
}
```

So `com.fasterxml.jackson.annotation.JsonSerializeAs` is essentially an alias for older `com.fasterxml.jackson.databind.annotation.JsonSerialize`.
Support is via `JacksonAnnotationIntrospector` class.

New tests need to be added to cover this, possibly copying existing ones for older annotation (`@JsonSerialize`).

**Comment by OrangeDog** [comment]
N.B. 3.1 will now fail to initialise with an annotations package older than 2.21.
```
Exception java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonSerializeAs
	at tools.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:37)
	at tools.jackson.databind.cfg.MapperBuilder.<clinit>(MapperBuilder.java:50)
	at tools.jackson.databind.json.JsonMapper.builder(JsonMapper.java:147)
```

**Comment by pjfanning** [comment]
You need jackson-annotations 2.21 jar. That is in the pom dependencies for jackson-databind 3.x.

**Comment by cowtowncoder** [comment]
@OrangeDog I would strongly recommend use of `jackson-bom` to help ensure consistent sets of dependencies.

**Comment by OrangeDog** [comment]
@pjfanning yes I know, I just wrote that.

@cowtowncoder I am using Spring Boot, which currently supports and imports both the Jackson 3 and 2 BOMs.
In order to get the CVE fix you have to override the versions for both of them, which is why I left this note here for others.

This perhaps counts as a breaking change you didn't notice. The `JacksonAnnotationIntrospector` could be using reflection instead of importing the new class directly.

**Comment by cowtowncoder** [comment]
@OrangeDog I am not sure how it could be seen as breaking change -- Jackson 3.1 components (databind etc) depend on `jackson-annotations` 2.21. There was never expectation that all 3.x versions would work with annotations 2.20.
