### ISSUE TITLE
NoClassDefFoundError since Jackson-Databind 3.2.0

### ISSUE THREAD

**Issue by S2Philipp** [FasterXML/jackson-databind#6051]
### Search before asking

- [x] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

I tried upgrading Jackson-Databind to 3.2.0 and a bunch of our tests fail now with the following error when we call JsonMapper.writeValueAsString().
As the same tests work fine with 3.1.4. this looks like a regression to me.

```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonApplyView

	at tools.jackson.databind.introspect.JacksonAnnotationIntrospector.findApplyView(JacksonAnnotationIntrospector.java:556)
	at tools.jackson.databind.introspect.POJOPropertyBuilder.findApplyView(POJOPropertyBuilder.java:830)
	at tools.jackson.databind.ser.PropertyBuilder.buildWriter(PropertyBuilder.java:249)
	at tools.jackson.databind.ser.BeanSerializerFactory._constructWriter(BeanSerializerFactory.java:883)
	at tools.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:610)
	at tools.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:317)
	at tools.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:241)
	at tools.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:174)
	at tools.jackson.databind.SerializationContext._createAndCacheUntypedSerializer(SerializationContext.java:1023)
	at tools.jackson.databind.SerializationContext.findValueSerializer(SerializationContext.java:829)
	at tools.jackson.databind.SerializationContext.findTypedValueSerializer(SerializationContext.java:625)
	at tools.jackson.databind.ser.SerializationContextExt.serializeValue(SerializationContextExt.java:296)
	at tools.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:1914)
	at tools.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:1857)
```

### Version Information

Works fine with 3.1.4, fails with 3.2.0.

### Reproduction

What we do is essentially just:

```Java
DEFAULT_OBJECT_MAPPER = JsonMapper.builderWithJackson2Defaults()
            .configure(FAIL_ON_UNKNOWN_PROPERTIES, false)
            .configure(WRITE_DATES_AS_TIMESTAMPS, false)
            .build();

DEFAULT_OBJECT_MAPPER.writeValueAsString(someObject);
```

**Comment by pjfanning** [comment]
com/fasterxml/jackson/annotation/JsonApplyView is in jackson-annotations 2.22

https://github.com/FasterXML/jackson-annotations/blob/ed91d619c38749471c376dbcde4112cbf157b305/src/main/java/com/fasterxml/jackson/annotation/JsonApplyView.java#L29

You should use jackson-bom or a build tool that obeys pom files for transitive lib management instead of relying on hard coding an old version of jackson-annotations.

**Comment by S2Philipp** [comment]
Sorry, I don't fully understand.
To my knowledge, Jackson 3 continues to use the old com.fasterxml.jackson.annotations and 2.22 is the latest stable release thereof, see: https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-annotations
Also, this suddenly broke with 3.2.0, which in its release notes says to use Annotations 2.22: https://github.com/FasterXML/jackson/wiki/Jackson-Release-3.2#annotations

**Comment by S2Philipp** [comment]
Sorry, I now get what you mean. Jackson 3.2.0 depends on Annotations 2.22.
I never read the term "harding" before.

**Comment by pjfanning** [comment]
I meant hard coding, just a typo.

**Comment by pjfanning** [comment]
https://repo1.maven.org/maven2/tools/jackson/jackson-bom/3.2.0/jackson-bom-3.2.0.pom depends on  jackson-annotations 2.22 which has the new JsonApplyView annotation class.

https://repo1.maven.org/maven2/tools/jackson/core/jackson-databind/3.2.0/jackson-databind-3.2.0.pom uses a property `jackson.version.annotations` and imports it from https://repo1.maven.org/maven2/tools/jackson/jackson-base/3.2.0/jackson-base-3.2.0.pom which imports it from https://repo1.maven.org/maven2/tools/jackson/jackson-bom/3.2.0/jackson-bom-3.2.0.pom
