### ISSUE TITLE
Jackson 2.7.x not usable with Android 2.3.3

### ISSUE THREAD

**Issue by mndfcked** [FasterXML/jackson-databind#1140]
The changes introduced in 7dce92ef6e990e43bc45f56aaa51ab18942bd1af lead to crashes on Android 2.3.3 due to missing JDK 7 compatibility. 
```
java.lang.NoSuchMethodError: java.util.Collections.emptyIterator
at com.fasterxml.jackson.databind.util.ClassUtil.emptyIterator(ClassUtil.java:24)
at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getConstructorParameters(POJOPropertyBuilder.java:383)
```

**Comment by cowtowncoder** [comment]
Right, this is #1134, to be fixed in 2.7.2. Also created https://github.com/FasterXML/jackson-jdk6-compat-test to hopefully guard against such accidental dependencies.

2.7.2 to be released during upcoming weekend, that is, within 3-4 days.
